name: Create Branch on Issue Move in Project

on:
  project_card:
    types: [moved]

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create branch from issue when moved to In Progress
        if: ${{ github.event.project_card.column_name == 'In Progress' }}
        run: |
          # Extraer la URL de la issue desde el payload del webhook
          ISSUE_URL=${{ github.event.project_card.content_url }}
          
          # Extraer el número de la issue desde la URL (por ejemplo, https://api.github.com/repos/OWNER/REPO/issues/1)
          ISSUE_NUMBER=$(echo $ISSUE_URL | sed 's/.*issues\///')
          
          # Crear una nueva rama con el número de la issue
          git checkout -b "issue-${ISSUE_NUMBER}"
          
          # Subir la rama a GitHub
          git push -u origin "issue-${ISSUE_NUMBER}"
